### ISSUE TITLE
Consider releasing on the Unreal Marketplace

### ISSUE THREAD

**Issue by seesemichaelj** [SRombauts/UEPlasticPlugin#113] opened 2022-09-12 21:48 UTC
After trying to onboard other teams with Plastic, I'm almost always "well go grab the latest plastic plugin from Github" because the engine doesn't get updated often (not that you don't update the engine plugin, but because the engine itself gets updated less frequently than the plugin does).

I'm curious if it would behoove users to remove the plugin from the official release of the engine and instead release updates on the Unreal Marketplace. Users would get prompted for an update in the launcher instead of having to recopy the plugin source from Github. Granted, this would be added overhead to the release process, but I figured it'd be worth considering!

I'd be willing to help if possible (I have scripts to help prepare the zips for the marketplace)

**Comment by SRombautsU** [comment] 2022-09-22 07:39
Hey Michael, thanks for suggesting this.

In fact, It has been on my roadmap from the start of the year! I thought it would have been more of a priority, but the reality is that not everyone agrees on this strategy. Just think of it: ideally nobody has nothing to install on top of UE5.1
T obvious worst part of it is that I wasn't able to push a better version of the plugin in UE5.0 because it came out just when I was getting starting on updating the plugin for UE5 :( 

Anyway, in the coming months there is probably two paths ahead;
1. either the plugin dev slows down (like it does already) and/or the unreal release schedule increases (like it should after UE5.1, eg to a version every 4 months)
2. or I'll have to try to push for the marketplace, but this would be only from UE5.2 onward (and as mentioned, it's not a clear win)

**Comment by SRombauts** [comment] 2022-12-20 10:12
Duplicate of #71

**Closed by SRombauts** 2022-12-20 10:12 UTC
Labels: question
